INDEX_DIR = $(HOME)/work/data/centrifuge-indexes

dolphin:
	./run_centrifuge.py -q $(HOME)/work/data/dolphin/fasta \
	-I $(INDEX_DIR) -i p_compressed+h+v -t fasta \
	-o $(HOME)/work/data/dolphin/centrifuge-out \
	-X 10000 -T 12
